//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ServiceModel.Channels;

namespace PersonService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SearchParameters", Namespace = "http://register.nhn.no/PR")]
    public partial class SearchParameters : object
    {

        private string AddressField;

        private System.Nullable<System.DateTime> DateOfBirthField;

        private string FirstNameField;

        private string LastNameField;

        private string MiddleNameField;

        private string MunicipalityCodeField;

        private System.Nullable<int> PageField;

        private string PostalPlaceField;

        private int ResultsPerPageField;

        private bool SearchFhNumberPersonsTooField;

        private string ZipCodeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MunicipalityCode
        {
            get
            {
                return this.MunicipalityCodeField;
            }
            set
            {
                this.MunicipalityCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Page
        {
            get
            {
                return this.PageField;
            }
            set
            {
                this.PageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalPlace
        {
            get
            {
                return this.PostalPlaceField;
            }
            set
            {
                this.PostalPlaceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultsPerPage
        {
            get
            {
                return this.ResultsPerPageField;
            }
            set
            {
                this.ResultsPerPageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SearchFhNumberPersonsToo
        {
            get
            {
                return this.SearchFhNumberPersonsTooField;
            }
            set
            {
                this.SearchFhNumberPersonsTooField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SearchResult", Namespace = "http://schemas.datacontract.org/2004/07/NHN.Contracts.Data")]
    public partial class SearchResult : object
    {

        private PersonService.Person[] PersonsField;

        private PersonService.Status StatusField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersonService.Person[] Persons
        {
            get
            {
                return this.PersonsField;
            }
            set
            {
                this.PersonsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersonService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Status", Namespace = "http://schemas.datacontract.org/2004/07/NHN.Contracts.Data")]
    public partial class Status : object
    {

        private int CodeField;

        private int CurrentPageField;

        private string MessageField;

        private string ReasonField;

        private int ResultsPerPageField;

        private int TotalPagesField;

        private int TotalResultsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage
        {
            get
            {
                return this.CurrentPageField;
            }
            set
            {
                this.CurrentPageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultsPerPage
        {
            get
            {
                return this.ResultsPerPageField;
            }
            set
            {
                this.ResultsPerPageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages
        {
            get
            {
                return this.TotalPagesField;
            }
            set
            {
                this.TotalPagesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalResults
        {
            get
            {
                return this.TotalResultsField;
            }
            set
            {
                this.TotalResultsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Person", Namespace = "http://register.nhn.no/PR")]
    public partial class Person : object
    {

        private PersonService.Address[] AddressesField;

        private string CitizenshipField;

        private string CitizenshipCodeField;

        private string CustodyField;

        private System.Nullable<System.DateTime> DateCitizenshipField;

        private System.Nullable<System.DateTime> DateCustodyField;

        private System.Nullable<System.DateTime> DateMaritalStatusField;

        private System.Nullable<System.DateTime> DateOfBirthField;

        private System.Nullable<System.DateTime> DateParentalResponsibilityField;

        private System.Nullable<System.DateTime> DateStatusField;

        private System.Nullable<System.DateTime> DateWithoutLegalCapacityField;

        private System.Nullable<System.DateTime> DateWorkPermitField;

        private string DufNoField;

        private string FathersNINField;

        private string GivenNameField;

        private System.Nullable<int> MaritalStatusField;

        private string MiddleNameField;

        private string MothersNINField;

        private string NINField;

        private string NewNINField;

        private string OldNINField;

        private System.Nullable<int> ParentalResponsibilityField;

        private System.Nullable<int> RegStatusField;

        private string SnField;

        private string SpouseNINField;

        private System.Nullable<int> StatusCountryCodeField;

        private string WithoutLegalCapacityField;

        private string WorkPermitField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public PersonService.Address[] Addresses
        {
            get
            {
                return this.AddressesField;
            }
            set
            {
                this.AddressesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Citizenship
        {
            get
            {
                return this.CitizenshipField;
            }
            set
            {
                this.CitizenshipField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CitizenshipCode
        {
            get
            {
                return this.CitizenshipCodeField;
            }
            set
            {
                this.CitizenshipCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Custody
        {
            get
            {
                return this.CustodyField;
            }
            set
            {
                this.CustodyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCitizenship
        {
            get
            {
                return this.DateCitizenshipField;
            }
            set
            {
                this.DateCitizenshipField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCustody
        {
            get
            {
                return this.DateCustodyField;
            }
            set
            {
                this.DateCustodyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateMaritalStatus
        {
            get
            {
                return this.DateMaritalStatusField;
            }
            set
            {
                this.DateMaritalStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateParentalResponsibility
        {
            get
            {
                return this.DateParentalResponsibilityField;
            }
            set
            {
                this.DateParentalResponsibilityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateStatus
        {
            get
            {
                return this.DateStatusField;
            }
            set
            {
                this.DateStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateWithoutLegalCapacity
        {
            get
            {
                return this.DateWithoutLegalCapacityField;
            }
            set
            {
                this.DateWithoutLegalCapacityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateWorkPermit
        {
            get
            {
                return this.DateWorkPermitField;
            }
            set
            {
                this.DateWorkPermitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DufNo
        {
            get
            {
                return this.DufNoField;
            }
            set
            {
                this.DufNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FathersNIN
        {
            get
            {
                return this.FathersNINField;
            }
            set
            {
                this.FathersNINField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GivenName
        {
            get
            {
                return this.GivenNameField;
            }
            set
            {
                this.GivenNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaritalStatus
        {
            get
            {
                return this.MaritalStatusField;
            }
            set
            {
                this.MaritalStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MothersNIN
        {
            get
            {
                return this.MothersNINField;
            }
            set
            {
                this.MothersNINField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIN
        {
            get
            {
                return this.NINField;
            }
            set
            {
                this.NINField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewNIN
        {
            get
            {
                return this.NewNINField;
            }
            set
            {
                this.NewNINField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldNIN
        {
            get
            {
                return this.OldNINField;
            }
            set
            {
                this.OldNINField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentalResponsibility
        {
            get
            {
                return this.ParentalResponsibilityField;
            }
            set
            {
                this.ParentalResponsibilityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RegStatus
        {
            get
            {
                return this.RegStatusField;
            }
            set
            {
                this.RegStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sn
        {
            get
            {
                return this.SnField;
            }
            set
            {
                this.SnField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpouseNIN
        {
            get
            {
                return this.SpouseNINField;
            }
            set
            {
                this.SpouseNINField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StatusCountryCode
        {
            get
            {
                return this.StatusCountryCodeField;
            }
            set
            {
                this.StatusCountryCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WithoutLegalCapacity
        {
            get
            {
                return this.WithoutLegalCapacityField;
            }
            set
            {
                this.WithoutLegalCapacityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkPermit
        {
            get
            {
                return this.WorkPermitField;
            }
            set
            {
                this.WorkPermitField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Address", Namespace = "http://register.nhn.no/PR")]
    public partial class Address : object
    {

        private string AddressLine1Field;

        private string AddressLine2Field;

        private string AddressLine3Field;

        private string ApartmentNumberField;

        private System.Nullable<int> BasicStatisticalUnitField;

        private string CadastralNumberField;

        private string CoAddressField;

        private string ConstituencyField;

        private string CountryField;

        private bool CurrentAddressField;

        private System.Nullable<System.DateTime> DateAdrFromField;

        private System.Nullable<System.DateTime> DatePostalTypeField;

        private string DistrictCodeField;

        private string DistrictNameField;

        private string HouseLetterField;

        private System.Nullable<int> HouseNumberField;

        private string MunicipalityField;

        private string NINField;

        private string PostalAddressField;

        private System.Nullable<System.DateTime> PostalAddressValidFromField;

        private string PostalCodeField;

        private string PostalPlaceField;

        private System.Nullable<int> PostalTypeField;

        private string PropertyNumberField;

        private string SchoolDistrictField;

        private string StField;

        private string StreetNameField;

        private string StreetNumberField;

        private System.Nullable<decimal> XCoordField;

        private System.Nullable<decimal> YCoordField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1
        {
            get
            {
                return this.AddressLine1Field;
            }
            set
            {
                this.AddressLine1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2
        {
            get
            {
                return this.AddressLine2Field;
            }
            set
            {
                this.AddressLine2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine3
        {
            get
            {
                return this.AddressLine3Field;
            }
            set
            {
                this.AddressLine3Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApartmentNumber
        {
            get
            {
                return this.ApartmentNumberField;
            }
            set
            {
                this.ApartmentNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BasicStatisticalUnit
        {
            get
            {
                return this.BasicStatisticalUnitField;
            }
            set
            {
                this.BasicStatisticalUnitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CadastralNumber
        {
            get
            {
                return this.CadastralNumberField;
            }
            set
            {
                this.CadastralNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoAddress
        {
            get
            {
                return this.CoAddressField;
            }
            set
            {
                this.CoAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Constituency
        {
            get
            {
                return this.ConstituencyField;
            }
            set
            {
                this.ConstituencyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CurrentAddress
        {
            get
            {
                return this.CurrentAddressField;
            }
            set
            {
                this.CurrentAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateAdrFrom
        {
            get
            {
                return this.DateAdrFromField;
            }
            set
            {
                this.DateAdrFromField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DatePostalType
        {
            get
            {
                return this.DatePostalTypeField;
            }
            set
            {
                this.DatePostalTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictCode
        {
            get
            {
                return this.DistrictCodeField;
            }
            set
            {
                this.DistrictCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictName
        {
            get
            {
                return this.DistrictNameField;
            }
            set
            {
                this.DistrictNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseLetter
        {
            get
            {
                return this.HouseLetterField;
            }
            set
            {
                this.HouseLetterField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HouseNumber
        {
            get
            {
                return this.HouseNumberField;
            }
            set
            {
                this.HouseNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Municipality
        {
            get
            {
                return this.MunicipalityField;
            }
            set
            {
                this.MunicipalityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIN
        {
            get
            {
                return this.NINField;
            }
            set
            {
                this.NINField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalAddress
        {
            get
            {
                return this.PostalAddressField;
            }
            set
            {
                this.PostalAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PostalAddressValidFrom
        {
            get
            {
                return this.PostalAddressValidFromField;
            }
            set
            {
                this.PostalAddressValidFromField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalPlace
        {
            get
            {
                return this.PostalPlaceField;
            }
            set
            {
                this.PostalPlaceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PostalType
        {
            get
            {
                return this.PostalTypeField;
            }
            set
            {
                this.PostalTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyNumber
        {
            get
            {
                return this.PropertyNumberField;
            }
            set
            {
                this.PropertyNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolDistrict
        {
            get
            {
                return this.SchoolDistrictField;
            }
            set
            {
                this.SchoolDistrictField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string St
        {
            get
            {
                return this.StField;
            }
            set
            {
                this.StField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName
        {
            get
            {
                return this.StreetNameField;
            }
            set
            {
                this.StreetNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetNumber
        {
            get
            {
                return this.StreetNumberField;
            }
            set
            {
                this.StreetNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> XCoord
        {
            get
            {
                return this.XCoordField;
            }
            set
            {
                this.XCoordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> YCoord
        {
            get
            {
                return this.YCoordField;
            }
            set
            {
                this.YCoordField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "LookupParameters", Namespace = "http://schemas.datacontract.org/2004/07/NHN.Contracts.Data")]
    public partial class LookupParameters : object
    {

        private System.Nullable<System.DateTime> DateField;

        private string NINField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIN
        {
            get
            {
                return this.NINField;
            }
            set
            {
                this.NINField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "IdentityChange", Namespace = "http://register.nhn.no/PR")]
    public partial class IdentityChange : object
    {

        private System.Nullable<System.DateTime> DateStatusField;

        private string NINField;

        private string OldNINField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateStatus
        {
            get
            {
                return this.DateStatusField;
            }
            set
            {
                this.DateStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIN
        {
            get
            {
                return this.NINField;
            }
            set
            {
                this.NINField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldNIN
        {
            get
            {
                return this.OldNINField;
            }
            set
            {
                this.OldNINField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AdvancedLookupParameters", Namespace = "http://register.nhn.no/PR")]
    public partial class AdvancedLookupParameters : object
    {

        private string[] ListOfNINField;

        private System.Collections.Generic.KeyValuePair<string, string>[] SearchConstraintsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ListOfNIN
        {
            get
            {
                return this.ListOfNINField;
            }
            set
            {
                this.ListOfNINField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] SearchConstraints
        {
            get
            {
                return this.SearchConstraintsField;
            }
            set
            {
                this.SearchConstraintsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://register.nhn.no/PR", ConfigurationName = "PersonService.IPersonService")]
    public interface IPersonService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://register.nhn.no/PR/IPersonService/Search", ReplyAction = "http://register.nhn.no/PR/IPersonService/SearchResponse")]
        System.Threading.Tasks.Task<PersonService.SearchResult> SearchAsync(PersonService.SearchParameters parameters);

        [System.ServiceModel.OperationContractAttribute(Action = "http://register.nhn.no/PR/IPersonService/GetPerson", ReplyAction = "http://register.nhn.no/PR/IPersonService/GetPersonResponse")]
        System.Threading.Tasks.Task<PersonService.Person> GetPersonAsync(PersonService.LookupParameters parameters);

        [System.ServiceModel.OperationContractAttribute(Action = "http://register.nhn.no/PR/IPersonService/GetPersons", ReplyAction = "http://register.nhn.no/PR/IPersonService/GetPersonsResponse")]
        System.Threading.Tasks.Task<PersonService.Person[]> GetPersonsAsync(string[] listOfNIN);

        [System.ServiceModel.OperationContractAttribute(Action = "http://register.nhn.no/PR/IPersonService/GetAddresses", ReplyAction = "http://register.nhn.no/PR/IPersonService/GetAddressesResponse")]
        System.Threading.Tasks.Task<PersonService.Address[]> GetAddressesAsync(PersonService.LookupParameters parameters);

        [System.ServiceModel.OperationContractAttribute(Action = "http://register.nhn.no/PR/IPersonService/GetChildren", ReplyAction = "http://register.nhn.no/PR/IPersonService/GetChildrenResponse")]
        System.Threading.Tasks.Task<PersonService.Person[]> GetChildrenAsync(string NIN);

        [System.ServiceModel.OperationContractAttribute(Action = "http://register.nhn.no/PR/IPersonService/GetIdentityChanges", ReplyAction = "http://register.nhn.no/PR/IPersonService/GetIdentityChangesResponse")]
        System.Threading.Tasks.Task<PersonService.IdentityChange[]> GetIdentityChangesAsync(System.DateTime from, System.Nullable<System.DateTime> to);

        [System.ServiceModel.OperationContractAttribute(Action = "http://register.nhn.no/PR/IPersonService/GetChanges", ReplyAction = "http://register.nhn.no/PR/IPersonService/GetChangesResponse")]
        System.Threading.Tasks.Task<PersonService.Person[]> GetChangesAsync(System.DateTime from, System.Nullable<System.DateTime> to);

        [System.ServiceModel.OperationContractAttribute(Action = "http://register.nhn.no/PR/IPersonService/GetAddressesAdvanced", ReplyAction = "http://register.nhn.no/PR/IPersonService/GetAddressesAdvancedResponse")]
        System.Threading.Tasks.Task<PersonService.Address[]> GetAddressesAdvancedAsync(PersonService.AdvancedLookupParameters parameters);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IPersonServiceChannel : PersonService.IPersonService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PersonServiceClient : System.ServiceModel.ClientBase<PersonService.IPersonService>, PersonService.IPersonService
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public PersonServiceClient(string endpointUrl, System.TimeSpan timeout, string username, string password) :
            base(PersonServiceClient.GetBindingForEndpoint(timeout), PersonServiceClient.GetEndpointAddress(endpointUrl))
        {
            this.ChannelFactory.Credentials.UserName.UserName = username;
            this.ChannelFactory.Credentials.UserName.Password = password;
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<PersonService.SearchResult> SearchAsync(PersonService.SearchParameters parameters)
        {
            return base.Channel.SearchAsync(parameters);
        }

        public System.Threading.Tasks.Task<PersonService.Person> GetPersonAsync(PersonService.LookupParameters parameters)
        {
            return base.Channel.GetPersonAsync(parameters);
        }

        public System.Threading.Tasks.Task<PersonService.Person[]> GetPersonsAsync(string[] listOfNIN)
        {
            return base.Channel.GetPersonsAsync(listOfNIN);
        }

        public System.Threading.Tasks.Task<PersonService.Address[]> GetAddressesAsync(PersonService.LookupParameters parameters)
        {
            return base.Channel.GetAddressesAsync(parameters);
        }

        public System.Threading.Tasks.Task<PersonService.Person[]> GetChildrenAsync(string NIN)
        {
            return base.Channel.GetChildrenAsync(NIN);
        }

        public System.Threading.Tasks.Task<PersonService.IdentityChange[]> GetIdentityChangesAsync(System.DateTime from, System.Nullable<System.DateTime> to)
        {
            return base.Channel.GetIdentityChangesAsync(from, to);
        }

        public System.Threading.Tasks.Task<PersonService.Person[]> GetChangesAsync(System.DateTime from, System.Nullable<System.DateTime> to)
        {
            return base.Channel.GetChangesAsync(from, to);
        }

        public System.Threading.Tasks.Task<PersonService.Address[]> GetAddressesAdvancedAsync(PersonService.AdvancedLookupParameters parameters)
        {
            return base.Channel.GetAddressesAdvancedAsync(parameters);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(System.TimeSpan timeout)
        {
            var httpsBinding = new System.ServiceModel.BasicHttpsBinding();
            httpsBinding.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;
            httpsBinding.Security.Mode = System.ServiceModel.BasicHttpsSecurityMode.Transport;

            var integerMaxValue = int.MaxValue;
            httpsBinding.MaxBufferSize = integerMaxValue;
            httpsBinding.MaxReceivedMessageSize = integerMaxValue;
            httpsBinding.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            httpsBinding.AllowCookies = true;

            httpsBinding.ReceiveTimeout = timeout;
            httpsBinding.SendTimeout = timeout;
            httpsBinding.OpenTimeout = timeout;
            httpsBinding.CloseTimeout = timeout;

            return httpsBinding;
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(string endpointUrl)
        {
            if (!endpointUrl.StartsWith("https://"))
            {
                throw new System.UriFormatException("The endpoint URL must start with https://.");
            }
            return new System.ServiceModel.EndpointAddress(endpointUrl);
        }
    }
}
